<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Categoria;

/**
 * CategoriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoriaRepository extends EntityRepository
{

	public function getCategoriasComoArray($tipo) {
		if ($tipo) {
			$qb = $this->getEntityManager()->createQueryBuilder()
				->select(array('c.id as id', 'c.descripcion as name'))
				->from(Categoria::ORM_ENTITY, 'c')
				->where("c.$tipo = 1")
			;
			$array = $qb->getQuery()->getArrayResult();
		}
		else {
			$array = array();
		}

		

		return $array;
	}

}
