<?php

namespace AppBundle\Repository;

/**
 * ConceptoObraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConceptoObraRepository extends \Doctrine\ORM\EntityRepository
{
}
