<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DetallePresupuestoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DetallePresupuestoRepository extends EntityRepository
{
}
