<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Obra;
/**
 * ObraRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ObraRepository extends EntityRepository
{

	public function getObrasComoArray($categoria) {
		if ($categoria) {
			$categoria = $categoria->getId();
			$qb = $this->getEntityManager()->createQueryBuilder()
			->select(array('o.id as id', 'o.descripcion as name'))
			->where("o.categoria = $categoria")
			->from(Obra::ORM_ENTITY, 'o');

			$array = $qb->getQuery()->getArrayResult();
		}
		else 
			$array = array();
		;

		return $array;
	}
}
